apiVersion: v1
kind: Pod
metadata:
  name: file-watcher-viniciusresende
  namespace: viniciusresende
spec:
  containers:
  - name: file-watcher
    image: viniciusalvesdefaria/file-watcher:latest
    volumeMounts:
    - mountPath: /app/dataset
      name: dataset-volume
    - mountPath: /app/k8s
      name: k8s-config
  volumes:
  - name: dataset-volume
    persistentVolumeClaim:
      claimName: project2-pvc2-viniciusresende
  - name: k8s-config
    configMap:
      name: model-job-configmap