apiVersion: batch/v1
kind: Job
metadata:
  name: process-dataset-job-viniciusresende-2f56cb3
  namespace: viniciusresende
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: dataset-processor
          image: viniciusalvesdefaria/spotify-fpgrowth:0.1
          command: ["sh", "setup.sh"]
          volumeMounts:
            - mountPath: /app/output
              name: persistent-volume
      restartPolicy: Never
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: project2-pvc2-viniciusresende
  backoffLimit: 4
