apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc2-viniciusresende
  namespace: viniciusresende
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: default-storage-class-viniciusresende
